import IDistributionPath from "./distributionPath";
import ISaleInvoice from "./saleInvoice";
import ISaleInvoiceDetail from "./saleInvoiceDetail";
import ISalePricingMethod from "./salePricingMethod";
import IUser from "./user";


export default interface IEmployee {
    id: number;
    code: string;
    identificationCode: string;
    firstName: string;
    sureName: string;
    fatherName: string;
    ssn: string;
    birthDate?: Date;
    farsiBirthDate: string;
    birthLocationId?: number;
    issueDate?: Date;
    farsiIssueDate: string;
    issueLocationId?: number;
    nationalCode: string;
    nationalityId?: number;
    phone: string;
    address: string;
    email: string;
    isMale?: boolean;
    housingTypeId?: number;
    marriageTypeId?: number;
    childrenNum?: number;
    transportTypeId?: number;
    workStatusId?: number;
    militaryServiceId?: number;
    educationLevelId?: number;
    educationFieldId?: number;
    bankAccountNumber: string;
    userId?: number;
    jobId?: number;
    jobBaseId?: number;
    jobBranchId?: number;
    jobCategoryId?: number;
    jobClassId?: number;
    jobGroupId?: number;
    rankId?: number;
    isLostLife?: boolean;
    bankId?: number;
    parentId?: number;
    preSalaryTypeId?: number;
    accountBranchId?: number;
    pathId?: number;
    canBePromoter?: boolean;
    pricingMethodId?: number;
    tag: string;
    leaveDate?: Date;
    farsiLeaveDate: string;
    startDate?: Date;
    farsiStartDate: string;
    isTreatmentLeave?: boolean;
    postalCode: string;
    incomingSalePercent?: number;
    cellPhone: string;
    deviceId: string;
    parent?: IEmployee;
    path?: IDistributionPath;
    pricingMethod?: ISalePricingMethod;
    user?: IUser;
    inverseParent: IEmployee[];
    tblSaleInvoiceDetail: ISaleInvoiceDetail[];
    tblSaleInvoicePromoter: ISaleInvoice[];
    tblSaleInvoicePromoterId2Navigation: ISaleInvoice[];
}